### ISSUE TITLE
Disable Scheduled publication on Pleroma as they doesnt work

### ISSUE THREAD

**Issue by bugsysop** [BDX-town/Mangane#106]
Context:

    Mangane goodcook-raccoon-b4be495
    Pleroma 2.4.4

Problem:

1) Scheduled posts never published
2) Error message when suppressing failled scheduled toots

![supp-error-mssg](https://user-images.githubusercontent.com/365281/208417979-0ae0cd02-896d-4b6b-b5ec-c88b629a858f.png)

**Comment by Cl0v1s** [comment]
Duplicate https://github.com/BDX-town/Mangane/issues/71

However, some of our users are already using scheduled posts, and I think they are working. cc @ymollard
If it's the case, maybe it's an issue with pleroma ? Are scheduled posts working on the vanilla pleroma FE ?

**Comment by bugsysop** [comment]
Sorry for the duplicate...

I think nonody have tried to use this when we used Pleroma FE

**Comment by bugsysop** [comment]
Not exactly the same as #71 here posts are _not_ published

**Comment by Cl0v1s** [comment]
If they arent published, I think it's more an issue with your backend than with Mangane itself. I'm waiting for Yann's answers since I know they are using scheduled posting on our instance :)

**Comment by ymollard** [comment]
Yes I've been using toot scheduling on bdx.town a couple of times, always successfully. And never met that error.

**Comment by bugsysop** [comment]
The problem is maybe from Pleroma part. There is an [open issue](https://git.pleroma.social/pleroma/pleroma-fe/-/issues/1046) about this.

**Comment by Cl0v1s** [comment]
This issue is to add the scheduling feature to the vanilla FE, if nobody is using it, there is maybe some problem with it. 

The Akkoma's changelog would tend in that direction: 
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/917518/208447497-7400000b-383e-4932-ad0e-6572bd8d4e97.png">
https://akkoma.dev/AkkomaGang/akkoma/src/branch/develop/CHANGELOG.md
Since it mention having added the endpoint allowing to schedule post, while pleroma just mention supporting the `scheduled_at` prop

**Comment by bugsysop** [comment]
On Pleroma FE and on Akkoma FE there is _no_ front UI to use Scheduled posts.

I think as it's a Pleroma problem, maybe we can close this issue and just add a note somewhere in documentation about the problem (info for Pleroma users)

**Comment by Cl0v1s** [comment]
Based on the feature detection system, we can deactivate that option for pleroma directly. Do you think it would be a good idea ?

**Comment by bugsysop** [comment]
Yes, ist’s frustrating to have an unfunctional function
