### ISSUE TITLE
Support Akkoma and/or Pleroma

### ISSUE THREAD

**Issue by bugsysop** [BDX-town/Mangane#107]
Plus une demande qu'un bug. 

Est-ce vraiment intéressant de reporter ici des problèmes avec **Pleroma** alors que vous développez Mangane explicitement pour **Akkoma** ?

Je pensais, à la lecture de la doc d'Akkoma, que les deux projets était encore largement compatibles, mais j'ai soudain un doute.

Je pose aussi la question par rapport à l'idée d'ajouter le [support de Mangane](https://github.com/YunoHost-Apps/pleroma_ynh/issues/220) à l'application Pleroma de Yunohost... C'est peut-être finalement pas une bonne idée

**Comment by Cl0v1s** [comment]
Apparently, and with what I know of Akkoma / Pleroma, as long as most of the API are compatible, there is not particular issue with fixing issue for both Pleroma and Akkoma. Akkoma mostly adds features, exposing them through new API endpoints. 

Moreover, Mangane already has a feature detection system allowing us to adapt the experience following what platform is used as a backend. 

We are speaking about Akkoma here since we are planning to add akkoma specific features to the project without breaking any existing compatibility.

**Comment by bugsysop** [comment]
Thanks for responding... Will continue to flood you with bug reports ;-)

**Comment by Cl0v1s** [comment]
Thanks for that ! It's hard to notice every issues since there is various configurations just as you noticed !
