### ISSUE TITLE
Local only publication 

### ISSUE THREAD

**Issue by Cl0v1s** [BDX-town/Mangane#11]
Proposer l'option, lors de la publication d'un message, de l'envoyer en local seulement, c'est à dire à la seule instance bdx.town.

Ce fonctionnement existe sur #GlitchSoc si ça peut aider : https://glitch-soc.github.io/docs/features/local-only-toots/

**Comment by Cl0v1s** [comment]
Apparently it's available on Akkoma https://docs.akkoma.dev/stable/installation/migrating_to_akkoma/

**Comment by Dehelssey** [comment]
Nice ! Je peux te maquetter ça dans l'UI du coup si tu veux ?

**Comment by Cl0v1s** [comment]
Je veux bien !

Le 22 novembre 2022 15:41:19 GMT+01:00, "Guérin" ***@***.***> a écrit :

**Comment by Cl0v1s** [comment]
Use the `visibility: local` property on new statuses to make a status local only
https://docs.akkoma.dev/stable/development/API/differences_in_mastoapi_responses/#statuses

**Comment by Dehelssey** [comment]
Argh, didn't design it sorry. At first, like i said on bdx.town. i thought it should probably be in the post privacy submenu, among public / unlisted ... but that might not the best solution since you might want a local only public or local only unlisted post (or even a "local only + followers only" ?) 

So i don't know... maybe more a checkbox below post !
