### ISSUE TITLE
fe.soapbox.pub and mangane on my instance

### ISSUE THREAD

**Issue by uandreew** [BDX-town/Mangane#191]
I decided to look at the soapbox in [fe.soapbox.pub](http://fe.soapbox.pub/), poked around in the settings and these settings switched to Mangane.
Even cryptocurrencies, which clovis said were deleted from Mangane, but they appeared in Mangane through the soapbox settings, how is this possible?
Is there any way to return the settings made in Mangane? (I can't change the color in mangane settings)

![image](https://user-images.githubusercontent.com/105280814/216703873-46957fec-5abb-4a9e-be82-9d9ffa116543.png)

**Comment by Dehelssey** [comment]
I'm not sure i get your problem... fe.soapbox is basically soapbox front-end as a client, where mangane is only a front-end.

Are you saying that settings you modified in fe.soapbox are saved in mangane and you can't undo them ?

**Comment by uandreew** [comment]
Yes, to undo the actions I did in fe.soapbox.pub, I had to remove some lines from "advanced" in Mangane Settings

![Screenshot_20230207-094229](https://user-images.githubusercontent.com/105280814/217182405-228f8d7a-f1c2-4f40-82d5-914473c9df49.png)

**Comment by Dehelssey** [comment]
fe.soapbox offers some features we didn't want or need in Mangane. But removing the feature in Mangane doesn't mean you can't activate it with another FE... 

Setting are mostly compatible since we share a common ground, therefore i'm not sure how much we can prevent settings set up in fe.soapbox to apply in Mangane...

Anyway, you should probably be able to easily undo what you did in fe.soapbox instead of trying to fix fe.soapbox settings in mangane directly...

**Comment by uandreew** [comment]
I don't understand how the features that have been removed from Mangane work, for example, crypto wallets.

I'm interested in how it is, why it is))

**Comment by muppeth** [comment]
I think mangane uses the same config as soapbox in the database so if you host both forntends and change for example config on soapbox web interface, that will reflect the change on mangane because they refer to the same entry in the database.
