### ISSUE TITLE
"Bell" subscribtion to account post show "mention" notification text

### ISSUE THREAD

**Issue by lapineige** [BDX-town/Mangane#197]
When you subscribe to an account and "activate the bell" to subscribe to any post, the notification for each post shows "@ someRandomAccount mentioned you" which is a bit confusing, instead of for instance "@ someRandomAccount published".

**Comment by Cl0v1s** [comment]
From what I see in the code, the template is `{name} just posted`. When you are speaking about notification, do you mean: 

* The ui in the notification view 
* The OS notification that you receive on your phone / desktop ?

**Comment by lapineige** [comment]
The ui in the notification view.

**Comment by Cl0v1s** [comment]
Ok apparently, Mangane support that notification type of should show `{name} just posted`

The issue seems to be with pleroma/akkoma, since there is no "status" notification type 
https://api.pleroma.social/#operation/NotificationController.index

While this type exists in mastodon API: https://docs.joinmastodon.org/methods/notifications/#get
