### ISSUE TITLE
Favicons of Mangane instances not showing on Calckey

### ISSUE THREAD

**Issue by Animaly0** [BDX-town/Mangane#235]
Les favicons d’instances akkoma + mangane ne s’affichent pas sur Calckey

Bug :
![image](https://github.com/BDX-town/Mangane/assets/52257781/574e3237-b1aa-4c05-954f-ac4f1352b768)

Comportement attendu :
![image](https://github.com/BDX-town/Mangane/assets/52257781/0792a5db-dfc9-4c4a-826b-fb61d4eeda0f)

**Comment by Cl0v1s** [comment]
Could you please provide the link of the requested missing ressource ? (Right click on the missing icon, and copy link)

**Comment by Cl0v1s** [comment]
After quick investigation, i'd say that's an issue with calckey, since the requested ressource (in that case, https://bdx.town/static/logo.svg) seems to be extracted from the manifest.json (https://bdx.town/manifest.json) instead of being extracted from a valid api endpoint (such as https://docs.joinmastodon.org/methods/instance/#v1)

In the case of bdx.town (https://bdx.town/api/v1/instance) points to https://bdx.town/media/0f5b93e45f12092673ea7955f927240a235119a802b3ea007cce471f9dccd98a.png which is a valid ressource
