### ISSUE TITLE
"Hide network" toggle in profile edition does not seems to work

### ISSUE THREAD

**Issue by Cl0v1s** [BDX-town/Mangane#262]
![690e77612b47b7cad55e175e76341bfcf060d6eff2bcd41930c8c4d5eb5ca3d2](https://github.com/BDX-town/Mangane/assets/917518/313bd596-4cba-4a83-93f6-754e28d82916)

This issue is reproduced on bdx.town too

**Comment by Dehelssey** [comment]
oh i just discovered this but the issue is already there 👀 

somehow related note : i'm really considering **completely removing those vanity metrics**, like number of followers. You've recently [boosted a post](https://bdx.town/@grunfink@comam.es/posts/Ag8UrVGmg1n8veYISW) that was also stating that this "popularity contest" was pointless and [my running poll](https://bdx.town/notice/AgBh2ROQqWjpcby5zs) seems to confirm that they're irrelevant to most users

I think i've already started to remove some numbers on the feed (like number of reactions / boosts) but we may want to go further to have a better product

**Comment by Cl0v1s** [comment]
I agree with those views from a personal standpoint. However, Mangaene is also used by other entities, and I'm uncertain if they agree with such points.

What I can propose (on another issue since it's a feature request) is to add an instance-wide setting to hide those metrics. Reading your poll also made me think that, while I don't necessarily consider counts to be relevant metrics, they can at least indicate if the profile is active, a frequent user, or has some credibility. What about replacing those metrics with badges that provide that type of information?

**Comment by Dehelssey** [comment]
I opened an issue so we can discuss this

**Comment by Cl0v1s** [comment]
fixed in https://github.com/BDX-town/Mangane/pull/296
