### ISSUE TITLE
black text on dark background

### ISSUE THREAD

**Issue by kendofriendo** [BDX-town/Mangane#316]
![qua5ao 1](https://github.com/BDX-town/Mangane/assets/39413174/435440ba-5213-42a4-ac70-f3732ec1bc54)

Running on docker with caddy.

Tried editing the config thusly but didn't seem to have an effect.

```
soc.website.win {
	reverse_proxy akkoma-akkoma-1:4000

	header {
		Content-Security-Policy "style-src 'self' 'unsafe-inline';"
	}
}
```

**Comment by paulo-roger** [comment]
I second this problem. Also with caddy and docker.

**Comment by Cl0v1s** [comment]
I'm not familiar with Caddy, but the issue is with said CSP headers not being applied correctly by your caddy configuration
Here is an answer of someone with a working configuration:

https://github.com/BDX-town/Mangane/issues/315#issuecomment-2071406572

Don't hesitate to explain your solution if you happen to get it working so I could add that to the documentation :)

**Comment by Cl0v1s** [comment]
From what I can read your configuration seems to differ from the one in doc:

```
Content-Security-Policy "upgrade-insecure-requests;script-src 'self';connect-src 'self' blob: https://example.com wss://example.com;media-src 'self' https:;img-src 'self' data: blob: https:;default-src 'none';base-uri 'self';frame-ancestors 'none';style-src 'self' 'unsafe-inline';font-src 'self';manifest-src 'self';"
```

https://github.com/BDX-town/Mangane?tab=readme-ov-file#messy-colors--style-configuration

**Comment by paulo-roger** [comment]
My solution was to run Mangane in another domain lol. I rather prefer to have the option to easily jump from a FE to another, so it is all good.

**Comment by Cl0v1s** [comment]
Thanks for your feedback !
