### ISSUE TITLE
Profile visibility

### ISSUE THREAD

**Issue by bugsysop** [BDX-town/Mangane#99]
After install all profiles where visible _only_ for connected user, even if this optionwas _not active_ in Mangane configuration 

Temporary solved the problem adding this line in the JSON file:

`"authenticatedProfile": false,`

**Comment by Cl0v1s** [comment]
Did you install Mangane on a fresh Akkoma/pleroma install or on a existing one ? :)

**Comment by bugsysop** [comment]
Install is on top of Pleroma (not Akkoma)

    Mangane goodcook-raccoon-b4be495
    Pleroma 2.4.4

Pleroma is running here from 2 or 3 years
The system is Debian/Yunohost

Installation of Mangane with the vanilla Admin Gui of Pleroma.

Sorry for Missing this information in my issue

**Comment by Cl0v1s** [comment]
No problem ! 
Did you use soapbox before ?

**Comment by bugsysop** [comment]
No ! I was waiting for this bad boy/gril of Mangane ;-)

**Comment by Cl0v1s** [comment]
Ok it's probably a missing default setting, nothing too complicated !

**Comment by BlackLight** [comment]
I can confirm that this issue is still there.

Fresh Akkoma installation, fresh Mangane installation.

Out of the box user profiles aren't visible to unauthenticated users, no matter their visibility settings or those on the instance level.

Couldn't find any flags on the UI to change the behaviour, and I've had to resort to manually adding `"authenticatedProfile": false` to the JSON.

**Comment by Cl0v1s** [comment]
The option in mangane config is there: 
![Capture d’écran 2024-03-26 à 19 46 49](https://github.com/BDX-town/Mangane/assets/917518/fde3a1f8-855c-4b51-b2b2-f2a73027e987)

It correctly changes the authenticatedProfile in the json

The default configuration is correcly setting that param: https://github.com/BDX-town/Mangane/blob/master/app/soapbox/normalizers/soapbox/soapbox_config.ts#L124
